services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  pixel-worlds-server:
    image: pixel-worlds-server:latest
    container_name: pixel-worlds-server
    depends_on:
      - mongodb
    network_mode: "host"
    restart: always

volumes:
  mongodb_data:
    driver: local
